import { AgentBlastRun } from "../core/types.js";

export function renderMarkdownReport(run: AgentBlastRun): string {
  const fixed = run.replay?.fixedFindingIds.length ?? 0;
  const remaining = run.replay?.remainingFindingIds.length ?? run.findings.length;
  const redTeam = run.redTeam;

  return [
    "# Agent Blast Report",
    "",
    `**Run:** ${run.id}`,
    `**Generated:** ${new Date().toISOString()}`,
    `**Target:** ${run.cwd}`,
    "",
    "## Summary",
    "",
    `- Findings: ${run.findings.length}`,
    `- Red-team cases: ${redTeam?.cases.length ?? 0}`,
    `- Red-team attempts: ${redTeam?.attempts ?? 0}`,
    `- Red-team failed: ${redTeam?.failed ?? 0}`,
    `- Attack success rate: ${formatRate(redTeam?.attackSuccessRate)}`,
    `- Patch proposals: ${run.patches.length}`,
    `- Replay fixed: ${fixed}`,
    `- Replay remaining: ${remaining}`,
    "",
    "Agent Blast does not claim the system is fully safe. This report only covers discovered findings and replay-backed changes.",
    "",
    "## Agent Map",
    "",
    `- Entrypoints: ${run.agentMap?.entrypoints.length ?? 0}`,
    `- Model calls: ${run.agentMap?.modelCalls.length ?? 0}`,
    `- Prompts: ${run.agentMap?.prompts.length ?? 0}`,
    `- Tools: ${run.agentMap?.tools.length ?? 0}`,
    `- Retrieval surfaces: ${run.agentMap?.retrieval.length ?? 0}`,
    "",
    "## Red Team",
    "",
    redTeam
      ? [
          `Mode: ${redTeam.mode}. Strategy: ${redTeam.strategy ?? "deterministic"}. Executor: ${redTeam.executor ?? "auto"}. Cases: ${redTeam.cases.length}. Attempts: ${redTeam.attempts ?? 0}. Failed: ${redTeam.failed}. Passed: ${redTeam.passed}. Needs review: ${redTeam.needsReview}. ASR: ${formatRate(redTeam.attackSuccessRate)}.`,
          "",
          redTeam.cases.length === 0
            ? "No red-team cases were generated."
            : "| ID | Class | Result | Attempts | Target | Root Cause |\n|---|---|---|---:|---|---|\n" +
              redTeam.cases
                .map((testCase) =>
                  [
                    testCase.id,
                    testCase.class,
                    testCase.result,
                    String(testCase.attempts?.length ?? 0),
                    testCase.targetPath ?? testCase.targetSurface,
                    testCase.rootCause ?? testCase.invariant
                  ]
                    .map(escapeTable)
                    .join(" | ")
                )
                .map((line) => `| ${line} |`)
                .join("\n")
        ].join("\n")
      : "Red-team suite has not been run yet.",
    "",
    "## Findings",
    "",
    run.findings.length === 0
      ? "No findings were generated by the current checks."
      : "| ID | Severity | Category | File | Status | Finding |\n|---|---|---|---|---|---|\n" +
        run.findings
          .map((finding) =>
            [
              finding.id,
              finding.severity,
              finding.category,
              finding.file ?? "",
              finding.status,
              finding.title
            ]
              .map(escapeTable)
              .join(" | ")
          )
          .map((line) => `| ${line} |`)
          .join("\n"),
    "",
    "## Patch Proposals",
    "",
    run.patches.length === 0
      ? "No patches were proposed."
      : run.patches
          .map((patch) => `### ${patch.id}: ${patch.title}\n\n- Target: \`${patch.targetPath}\`\n- Status: ${patch.status}\n- Rationale: ${patch.rationale}`)
          .join("\n\n"),
    "",
    "## Replay",
    "",
    run.replay
      ? [
          `Replay completed. Fixed: ${run.replay.fixedFindingIds.join(", ") || "none"}. Remaining: ${run.replay.remainingFindingIds.join(", ") || "none"}.`,
          run.replay.fixedRedTeamCaseIds || run.replay.remainingRedTeamCaseIds
            ? `Red-team fixed: ${run.replay.fixedRedTeamCaseIds?.join(", ") || "none"}. Red-team remaining: ${run.replay.remainingRedTeamCaseIds?.join(", ") || "none"}. ASR before: ${formatRate(run.replay.redTeamAttackSuccessRateBefore)}. ASR after: ${formatRate(run.replay.redTeamAttackSuccessRateAfter)}.`
            : ""
        ]
          .filter(Boolean)
          .join("\n")
      : "Replay has not been run yet.",
    ""
  ].join("\n");
}

export function renderHtmlReport(run: AgentBlastRun): string {
  const fixed = run.replay?.fixedFindingIds.length ?? 0;
  const remaining = run.replay?.remainingFindingIds.length ?? run.findings.length;
  const redTeam = run.redTeam;
  const findingRows = run.findings
    .map(
      (finding) =>
        `<tr><td>${escapeHtml(finding.id)}</td><td class="${finding.severity}">${escapeHtml(finding.severity)}</td><td>${escapeHtml(finding.category)}</td><td>${escapeHtml(finding.file ?? "")}</td><td>${escapeHtml(finding.status)}</td><td>${escapeHtml(finding.title)}</td></tr>`
    )
    .join("");
  const redTeamRows = (redTeam?.cases ?? [])
    .map(
      (testCase) =>
        `<tr><td>${escapeHtml(testCase.id)}</td><td>${escapeHtml(testCase.class)}</td><td class="${escapeHtml(testCase.result)}">${escapeHtml(testCase.result)}</td><td>${testCase.attempts?.length ?? 0}</td><td>${escapeHtml(testCase.targetPath ?? testCase.targetSurface)}</td><td>${escapeHtml(testCase.rootCause ?? testCase.invariant)}</td></tr>`
    )
    .join("");

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Agent Blast Report</title>
  <style>
    :root { color-scheme: dark; --bg: #0b0f12; --surface: #11181d; --text: #e7eef2; --muted: #8ea1ad; --accent: #38d9c6; --border: #24323a; --risk: #ffb86b; --high: #ff6b6b; }
    body { margin: 0; background: var(--bg); color: var(--text); font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace; }
    main { max-width: 1120px; margin: 0 auto; padding: 40px 24px; }
    header { border-bottom: 1px solid var(--border); padding-bottom: 18px; margin-bottom: 28px; }
    h1 { margin: 0 0 8px; font-size: 28px; color: var(--accent); }
    h2 { margin-top: 32px; font-size: 16px; text-transform: uppercase; letter-spacing: .08em; color: var(--muted); }
    .summary { display: grid; grid-template-columns: repeat(5, minmax(0, 1fr)); gap: 12px; }
    .metric { background: var(--surface); border: 1px solid var(--border); padding: 14px; }
    .metric strong { display: block; font-size: 24px; color: var(--text); }
    table { width: 100%; border-collapse: collapse; background: var(--surface); border: 1px solid var(--border); }
    th, td { text-align: left; padding: 10px; border-bottom: 1px solid var(--border); vertical-align: top; }
    th { color: var(--muted); font-weight: 600; }
    .high, .critical { color: var(--high); }
    .medium { color: var(--risk); }
    .note { color: var(--muted); }
    @media (max-width: 760px) { .summary { grid-template-columns: 1fr 1fr; } main { padding: 24px 14px; } table { font-size: 12px; } }
  </style>
</head>
<body>
  <main>
    <header>
      <h1>Agent Blast Report</h1>
      <div class="note">Run ${escapeHtml(run.id)} · ${escapeHtml(run.cwd)}</div>
    </header>
    <section class="summary">
      <div class="metric"><span>Findings</span><strong>${run.findings.length}</strong></div>
      <div class="metric"><span>Red-team failed</span><strong>${redTeam?.failed ?? 0}</strong></div>
      <div class="metric"><span>Attempts</span><strong>${redTeam?.attempts ?? 0}</strong></div>
      <div class="metric"><span>ASR</span><strong>${formatRate(redTeam?.attackSuccessRate)}</strong></div>
      <div class="metric"><span>Patches</span><strong>${run.patches.length}</strong></div>
      <div class="metric"><span>Replay fixed</span><strong>${fixed}</strong></div>
      <div class="metric"><span>Remaining</span><strong>${remaining}</strong></div>
    </section>
    <p class="note">Agent Blast does not claim the system is fully safe. This report only covers discovered findings and replay-backed changes.</p>
    <h2>Agent Map</h2>
    <p>Entrypoints: ${run.agentMap?.entrypoints.length ?? 0} · Model calls: ${run.agentMap?.modelCalls.length ?? 0} · Prompts: ${run.agentMap?.prompts.length ?? 0} · Tools: ${run.agentMap?.tools.length ?? 0} · Retrieval: ${run.agentMap?.retrieval.length ?? 0}</p>
    <h2>Red Team</h2>
    <p>${redTeam ? `Mode: ${escapeHtml(redTeam.mode)} · Strategy: ${escapeHtml(redTeam.strategy ?? "deterministic")} · Executor: ${escapeHtml(redTeam.executor ?? "auto")} · Cases: ${redTeam.cases.length} · Attempts: ${redTeam.attempts ?? 0} · Failed: ${redTeam.failed} · Passed: ${redTeam.passed} · Needs review: ${redTeam.needsReview} · ASR: ${formatRate(redTeam.attackSuccessRate)}` : "Red-team suite has not been run yet."}</p>
    <table><thead><tr><th>ID</th><th>Class</th><th>Result</th><th>Attempts</th><th>Target</th><th>Root Cause</th></tr></thead><tbody>${redTeamRows || "<tr><td colspan='6'>No red-team cases generated.</td></tr>"}</tbody></table>
    <h2>Findings</h2>
    <table><thead><tr><th>ID</th><th>Severity</th><th>Category</th><th>File</th><th>Status</th><th>Finding</th></tr></thead><tbody>${findingRows || "<tr><td colspan='6'>No findings generated.</td></tr>"}</tbody></table>
    <h2>Replay</h2>
    <p>${run.replay ? `Fixed: ${escapeHtml(run.replay.fixedFindingIds.join(", ") || "none")} · Remaining: ${escapeHtml(run.replay.remainingFindingIds.join(", ") || "none")} · Red-team fixed: ${escapeHtml(run.replay.fixedRedTeamCaseIds?.join(", ") || "none")} · Red-team remaining: ${escapeHtml(run.replay.remainingRedTeamCaseIds?.join(", ") || "none")} · ASR before: ${formatRate(run.replay.redTeamAttackSuccessRateBefore)} · ASR after: ${formatRate(run.replay.redTeamAttackSuccessRateAfter)}` : "Replay has not been run yet."}</p>
  </main>
</body>
</html>`;
}

function escapeTable(value: string): string {
  return value.replace(/\|/g, "\\|").replace(/\n/g, " ");
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

function formatRate(value: number | undefined): string {
  if (typeof value !== "number" || !Number.isFinite(value)) return "0%";
  return `${Math.round(value * 1000) / 10}%`;
}
